# Chapter 3 : It starts with a tensor
### 1. Create a tensor `a` from `list(range(9))`. Predict and then check the size, offset, and stride.
* Create a new tensor using `b = a.view(3, 3)`. What does view do? Check that `a` and `b` share the same storage.
* Create a tensor `c = b[1:,1:]`. Predict and then check the size, offset, and stride.

In [52]:
import torch
a = list(range(9))
a = torch.tensor(a)
print(a, a.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]) torch.Size([9])


In [53]:
b = a.view(3,3)
print(b, b.shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) torch.Size([3, 3])


In [54]:
print(a.storage(),'\n\n', b.storage())

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9] 

  0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]


**1a.** The `view` function rearange a tensor.`view(n,m)` return an exception if n\*m ≠ `a.shape[0]`.
We also show that `b` is just an other way to see `a`, since they both share the same storage.

In [55]:
c = b[1:,1:]
c

tensor([[4, 5],
        [7, 8]])

**1b.** Here, `c` seems to be a part of the tensor `b`. So they should share the same storage. However, elements in `c` do not follow the same structure and do not start with the same element. So, we should expect a modification of the `stride` and `offset` informations.

In [56]:
print("c storage : \n", c.storage())
print("\n c offset : \n", c.storage_offset())
print("c stride : \n", c.stride())

c storage : 
  0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]

 c offset : 
 4
c stride : 
 (3, 1)


As we predicted, `c` shares the same storage than `a` and `b` since it can be see as a part of tensors `a` or `b`. \
Also, it starts with the number 4 so the `offset` is 4 \
And then, `stride(3,1)` because it takes 3 positions in the storage to go to the next row and it takes 1 position in the storage to go to the next column.

### 2. Pick a mathematical operation like cosine or square root. Can you find a corresponding function in the torch library?
* Apply the function element-wise to `a`. Why does it return an error?
* What operation is required to make the function work?
* Is there a version of your function that operates in place?

In [57]:
a.dtype

torch.int64

In [58]:
#a_sqrt = torch.sqrt(a)
### It returns an exception because dtype(a) = int64 and it should be a float
a.dtype

torch.int64

In [59]:
# Float32 is commonly use in Pytorch
a_float32 = a.to(torch.float32)
a_float32.dtype

torch.float32

In [60]:
a_sqrt = torch.sqrt(a_float32)
a_sqrt # It works !

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])

In [61]:
# We could also use the inplace function as well
torch.sqrt_(a_float32)
a_float32

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])